### ISSUE TITLE
RFE: support for homeassistant autodiscovery

### ISSUE THREAD

**Issue by NeilHanlon** [DPHacks/picow-air#1]
Heya! I just got my order from Tindie the other day and all is working well! I wanted to open an issue here about autodiscovery for homeassistant before I started working on implementing it, in case there was some preexisting work or something I was missing.

I've managed to get my sensor into HA using the following config in configuration.yaml, and I suspect it shouldn't be that hard to add a configuration setting which would emit an MQTT message to the right place to create the entities automagically--which I'm happy to poke at assuming it's not already underway :) 

```
sensor:
  - state_topic: "enviro/picoair"
    name: "PM100 Environment"
    unit_of_measurement: 'µg/m³'
    value_template: "{{ value_json['pm100 env'] }}"

  - state_topic: "enviro/picoair"
    name: "Particles 0.3µm"
    unit_of_measurement: 'particles/cm³'
    value_template: "{{ value_json['particles 03um'] }}"

  - state_topic: "enviro/picoair"
    name: "PM100 Standard"
    unit_of_measurement: 'µg/m³'
    value_template: "{{ value_json['pm100 standard'] }}"

  - state_topic: "enviro/picoair"
    name: "Particles 2.5µm"
    unit_of_measurement: 'particles/cm³'
    value_template: "{{ value_json['particles 25um'] }}"

  - state_topic: "enviro/picoair"
    name: "PM2.5 Standard"
    unit_of_measurement: 'µg/m³'
    value_template: "{{ value_json['pm25 standard'] }}"

  - state_topic: "enviro/picoair"
    name: "PM10 Environment"
    unit_of_measurement: 'µg/m³'
    value_template: "{{ value_json['pm10 env'] }}"

  - state_topic: "enviro/picoair"
    name: "PM10 Standard"
    unit_of_measurement: 'µg/m³'
    value_template: "{{ value_json['pm10 standard'] }}"

  - state_topic: "enviro/picoair"
    name: "PM2.5 Environment"
    unit_of_measurement: 'µg/m³'
    value_template: "{{ value_json['pm25 env'] }}"

  - state_topic: "enviro/picoair"
    name: "Particles 0.5µm"
    unit_of_measurement: 'particles/cm³'
    value_template: "{{ value_json['particles 05um'] }}"

  - state_topic: "enviro/picoair"
    name: "Particles 1.0µm"
    unit_of_measurement: 'particles/cm³'
    value_template: "{{ value_json['particles 10um'] }}"

  - state_topic: "enviro/picoair"
    name: "Particles 100µm"
    unit_of_measurement: 'particles/cm³'
    value_template: "{{ value_json['particles 100um'] }}"

  - state_topic: "enviro/picoair"
    name: "Particles 50µm"
    unit_of_measurement: 'particles/cm³'
    value_template: "{{ value_json['particles 50um'] }}"
```

Thanks for the work on this!
